// <auto-generated />
namespace CorePlugin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_coredb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_coredb));
        
        string IMigrationMetadata.Id
        {
            get { return "202202250349233_update_coredb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
