// <auto-generated />
namespace Client.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class activity_mj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(activity_mj));
        
        string IMigrationMetadata.Id
        {
            get { return "202111270813270_activity_mj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
