// <auto-generated />
namespace Client.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class customer_black : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customer_black));
        
        string IMigrationMetadata.Id
        {
            get { return "202111260550235_customer_black"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
