// <auto-generated />
namespace Client.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class member_isdelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(member_isdelete));
        
        string IMigrationMetadata.Id
        {
            get { return "202111270633101_member_isdelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
